# Basics
baseURL: https://fachinformatikerpruefungsvorbereitung.de
title: Fachinformatiker Pr√ºfungsvorbereitung
enableGitInfo: true

# Modules
module:
  imports:
    - path: github.com/imfing/hextra

# Language
languageCode: de
defaultContentLanguage: de
defaultContentLanguageInSubdir: false
contentDir: "content/de"
enableMissingTranslationPlaceholders: true

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  theme:
    # light | dark | system
    default: system
    displayToggle: true
  editURL:
    enable: true
    base: "https://github.com/Fachinformatiker-Prufungsvorbereitung/Fachinformatiker-Pruefungsvorbereitung/edit/main/content"
  navbar:
    displayTitle: true
    displayLogo: false

# Menu
menu:
  main:
    - name: Search
      params:
        type: search
      weight: 20
    - name: GitHub
      weight: 70
      url: "https://github.com/Fachinformatiker-Prufungsvorbereitung/Fachinformatiker-Pruefungsvorbereitung"
      params:
        icon: github
    - name: News
      weight: 50
      url: https://lna-dev.net/de/tags/fachinformatiker-pr%C3%BCfungsvorbereitung/
      params:
        icon: newspaper

# Outputs
outputs:
  section:
    - HTML
    - RSS
    - print

# SEO
sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5

enableRobotsTXT: true

privacy:
  youtube:
    disable: false
    privacyEnhanced: true

